const data = `[
    {
    "web_pages":[
    "http://www.ablaikhan.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "ablaikhan.kz"
    ],
    "name":"Abylai Khan University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.agriun.almaty.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "agriun.almaty.kz"
    ],
    "name":"Kazak State University of Agriculture",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.aktsu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "aktsu.kz"
    ],
    "name":"Aktau State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.atgu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "atgu.kz"
    ],
    "name":"Atyrau State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.ektu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "ektu.kz"
    ],
    "name":"East Kazakstan State Technical University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.enu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "enu.kz"
    ],
    "name":"L.N. Gumilyov Eurasian National University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.eurazir.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "eurazir.kz"
    ],
    "name":"Eurasian Institute of market",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kau.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kau.kz"
    ],
    "name":"Kazak American University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kazeu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kazeu.kz"
    ],
    "name":"Turar Ryskulov Kazakh Economic University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kaznpu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kaznpu.kz"
    ],
    "name":"Abai State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kazntu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kazntu.kz"
    ],
    "name":"Kazak National Technical University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kaznu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kaznu.kz"
    ],
    "name":"Al-Farabi Kazakh National University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kbtu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kbtu.kz"
    ],
    "name":"Kazakh British Technical University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kimep.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kimep.kz"
    ],
    "name":"Kazakhstan Institute of Management, Economics, and Strategic Research",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.kstu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "kstu.kz"
    ],
    "name":"Karaganda State Technical University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.ksu.kst.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "ksu.kst.kz"
    ],
    "name":"Kostanai State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.ksu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "ksu.kz"
    ],
    "name":"Karaganda State Buketov University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.nkzu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "nkzu.kz"
    ],
    "name":"North Kazakhstan State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.psu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "psu.kz"
    ],
    "name":"Pavlodar University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.sdu.edu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "sdu.edu.kz"
    ],
    "name":"Suleyman Demirel University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.semgu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "semgu.kz"
    ],
    "name":"Semey State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.sgma.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "sgma.kz"
    ],
    "name":"Semey State Medical University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.turkistan.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "turkistan.kz"
    ],
    "name":"International Kazakh-Turkish University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.uib.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "uib.kz"
    ],
    "name":"University of International Business",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.vkgu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "vkgu.kz"
    ],
    "name":"East Kazakhstan State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.wkau.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "wkau.kz"
    ],
    "name":"Western Kazakhstan Agricultural University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.zhezu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "zhezu.kz"
    ],
    "name":"Zhezkazgan Baikonurov University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "http://www.zhgu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "zhgu.kz"
    ],
    "name":"Zhetysu State University",
    "country":"Kazakhstan"
    },
    {
    "web_pages":[
    "https://nu.edu.kz/"
    ],
    "alpha_two_code":"KZ",
    "state-province":null,
    "domains":[
    "nu.edu.kz"
    ],
    "name":"Nazarbayev University",
    "country":"Kazakhstan"
    }
    ]`;